### ISSUE TITLE
hashes not matching canonical test output

### ISSUE THREAD

**Issue by heapwolf** [datcxx/sodium#1]
Running the tests...

```bash
$build test
```

Outputs the following, but does not match the output from [these][0] tests. The lengths of the hashes match.

```tap
TAP version 13
ok 1 - true is true
ok 2 - initialized sodium
ok 3 - correct number of bytes
not ok 4 - hashed buffer
  ---
  operator: equal
  expected: 511bc81dde11180838c562c82bb35f823f46061ebde4a955c27b3f489cf1e03
  actual:   b5da441cfe72ae042ef4d2b17742907f675de4da57462d4c3609c2e2ed755970
  ...
not ok 5 - hashed buffer min
  ---
  operator: equal
  expected: 3895c59e4aeb0903396b5be3fbec69fe
  actual:   9bbbb7410fa6464a1a6a216919179455
  ...
not ok 6 - hashed buffer max
  ---
  operator: equal
  expected: 7dfdb888af71eae0e6a6b751e8e3413d767ef4fa52a7993daa9ef097f7aa3d949199c113caa37c94f80cf3b22f7d9d6e4f5def4ff927830cffe4857c34be3d89
  actual:   a2764d133a16816b5847a737a786f2ece4c148095c5faa73e24b4cc5d666c3e45ec271504e14dc6127ddfce4e144fb23b91a6f7b04b53d695502290722953b0f
  ...
1..6
# tests 6
# pass  3
# fail  3
```

The buffer class holds a value of `std::vector<uint8_t>`, essentially a vector of `unsigned char`, this should work with node's buffer struct which holds a `char*`.

[0]:https://github.com/sodium-friends/sodium-native/blob/master/test/crypto_generichash.js#L3-L21

**Comment by heapwolf** [comment]
cc @emilbayes

**Comment by emilbayes** [comment]
Not sure, code looks alright, so it must be something with the data coming out of the buffers?
Here are more test vectors, including the official ones: https://github.com/emilbayes/blake2b#test-vectors

**Comment by heapwolf** [comment]
So, this boiled down to `Hello, world!` vs `Hello, World!` as a test string. Someone please kill me. :roll_eyes:

**Comment by emilbayes** [comment]
Haha, get on the test vectors instead 😄
